# Generated by Django 4.2 on 2025-05-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(null=True, upload_to='actor_images/'),
        ),
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(null=True, upload_to='director_images/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(null=True, related_name='directed_movies', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='director',
            name='nationality',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
