# Generated by Django 4.2 on 2025-05-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_photo_director_photo_alter_actor_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
    ]
