# Generated by Django 4.2 on 2025-05-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_director_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(null=True, upload_to='movie_images/'),
        ),
    ]
